workflows:
  ios-testflight:
    name: iOS TestFlight Release
    instance_type: mac_mini_m2
    max_build_duration: 120
    
    integrations:
      app_store_connect: key_for_codemagic
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.athleon.shotmetrix"
        APP_STORE_APP_ID: 6755712389
    
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
          
      - name: Install CocoaPods
        script: | 
          find . -name "Podfile" -execdir pod install \;
          
      - name: Build iOS app
        script: | 
          flutter build ipa --release \
            --build-name=1.0.0 \
            --export-method app-store
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - suhaibvp9895@gmail.com
        notify:
          success: true
          failure: true
          
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
