// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqI_ZOh2tN3E7bX8ZUzL0XtmIt5E4IZHY',
    appId: '1:767461333659:web:ca8575127d9f353738c43e',
    messagingSenderId: '767461333659',
    projectId: 'myshoot-8a6cb',
    authDomain: 'myshoot-8a6cb.firebaseapp.com',
    storageBucket: 'myshoot-8a6cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZjYCyp9BkhgkskovW0XPJSe0QfUoSX_s',
    appId: '1:767461333659:android:9324b7d3566ab35f38c43e',
    messagingSenderId: '767461333659',
    projectId: 'myshoot-8a6cb',
    storageBucket: 'myshoot-8a6cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7JXghB7eLjwO4CHDy_hYt2kQF0g41XVg',
    appId: '1:767461333659:ios:65efc7533b183df438c43e',
    messagingSenderId: '767461333659',
    projectId: 'myshoot-8a6cb',
    storageBucket: 'myshoot-8a6cb.firebasestorage.app',
    iosBundleId: 'com.example.myshoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7JXghB7eLjwO4CHDy_hYt2kQF0g41XVg',
    appId: '1:767461333659:ios:65efc7533b183df438c43e',
    messagingSenderId: '767461333659',
    projectId: 'myshoot-8a6cb',
    storageBucket: 'myshoot-8a6cb.firebasestorage.app',
    iosBundleId: 'com.example.myshoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqI_ZOh2tN3E7bX8ZUzL0XtmIt5E4IZHY',
    appId: '1:767461333659:web:532e82aa4970a48f38c43e',
    messagingSenderId: '767461333659',
    projectId: 'myshoot-8a6cb',
    authDomain: 'myshoot-8a6cb.firebaseapp.com',
    storageBucket: 'myshoot-8a6cb.firebasestorage.app',
  );
}
